config/routes.rb
ViewTemplateInheritance::Application.routes.draw do
  root 'home#show'
  resources :categories, only: :index
  resources :courses, only: :index
  resources :tutors, only: :index
  namespace :admin do
    resources :tutors, only: :index
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
  end
end

app/controllers/admin/tutors_controller.rb
module Admin
  class TutorsController < BaseController
    def index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  def index
  end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/tutors_helper.rb
module Admin::TutorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/admin/base/_appended_menu.html.erb
<li><b><a href='#'>Add new Category</a></b></li>
<li><b><a href='#'>Add new Course</a></b></li>
<li><b><a href='#'>Add new Tutor</a></b></li>

app/views/admin/tutors/index.html.erb
<h1>Admin::Tutors#index</h1>
<i>Rendering menu partial below: </i><br/>
<%= render 'menu' %>

app/views/application/_menu.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Categories", categories_path %></li>
  <li><%= link_to "Courses", courses_path %></li>
  <li><%= link_to "Tutors", tutors_path %></li>
  <%= render 'appended_menu' %>
</ul>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<i>Rendering menu partial below: </i>
<%= render 'menu' %>

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<i>Rendering menu partial below: </i>
<%= render 'menu' %>

app/views/home/show.html.erb
<h1>View Template Inheritance Example</h1>
<h2>Click on the links below to see the menu change (or not!)</h2>
<h3>Readme notes and tweetegy blog post explain more</h3>
<h4>Rendering menu below</h4>
<%= render 'menu' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ViewTemplateInheritance</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tutors/_appended_menu.html.erb
<li><b><a href='#'>Apply for teaching position!</a></b></li>

app/views/tutors/index.html.erb
<h1>Tutors#index</h1>
<i>Rendering menu partial below: </i><br/>
<b>NOTE: this should have an extra menu item!</b>
<%= render 'menu' %>